# frozen_string_literal: true
class CompleteCourseReviewParity < ActiveRecord::Migration[7.2]
  def up
    add_column :river_courses_courses, :group_key, :text
    add_column :river_courses_reviews, :hidden_reason, :text
    add_column :river_courses_comments, :hidden_reason, :text
    execute <<~SQL
      UPDATE river_courses_courses c SET group_key = jsonb_build_array(
        COALESCE(NULLIF(c.code, ''), split_part(c.class_no, '.', 1)), c.title,
        COALESCE((SELECT string_agg(btrim(n), ';' ORDER BY btrim(n) COLLATE "C") FROM unnest(string_to_array(c.teachers, ';')) n WHERE btrim(n) <> ''), '')
      )::text;
    SQL
    # Canonical compact JSON is generated by the model/importer; backfill identically.
    rows = select_all('SELECT id, code, class_no, title, teachers FROM river_courses_courses')
    rows.each do |r|
      key = [r['code'].presence || r['class_no'].split('.').first, r['title'], r['teachers'].split(';').map(&:strip).reject(&:empty?).sort.join(';')].to_json
      execute "UPDATE river_courses_courses SET group_key=#{quote(key)} WHERE id=#{r['id'].to_i}"
    end
    change_column_null :river_courses_courses, :group_key, false
    add_index :river_courses_courses, :group_key
    add_index :river_courses_reviews, [:status, :created_at]
    add_index :river_courses_reviews, :user_id
    add_index :river_courses_comments, :user_id
    add_index :river_courses_legacies, [:target_kind, :target_id]
  end
  def down
    remove_index :river_courses_legacies, [:target_kind, :target_id]
    remove_index :river_courses_comments, :user_id
    remove_index :river_courses_reviews, :user_id
    remove_index :river_courses_reviews, [:status, :created_at]
    remove_column :river_courses_comments, :hidden_reason
    remove_column :river_courses_reviews, :hidden_reason
    remove_column :river_courses_courses, :group_key
  end
end
